let frase1 = " Hola mundo ";
let frase2 = "Nuevo e increible";

console.log("Estas son las frases de ejemplo: frase1(" + frase1 + ") frase2(" + frase2 + ")");

console.log("1 - at() con " + frase1 + " resultado: " + frase1.at(1));
console.log("2 - charAt() con " + frase1 + " resultado: " + frase1.charAt(2));
console.log("3 - charCodeAt() con " + frase1 + " resultado: " + frase1.charCodeAt(1) + " unicode de " + frase1.at(1));
console.log("4 - codePointAt() con " + frase1 + " resultado: " + frase1.codePointAt(2) + " unicode de " + frase1.charAt(2));
console.log("5 - concat() con " + frase1 + " y " + frase2 + " resultado: " + frase1.concat(" | ", frase2));
console.log("6 - constructor con " + frase1 + " resultado: " + frase1.constructor);
console.log("7 - endsWith() con " + frase1 + " resultado: " + frase1.endsWith("mundo "));
console.log("8 - fromChardCode() resultado: " + String.fromCharCode(72, 111, 108, 97));
console.log("9 - includes() con "  + frase1 + " resultado: " + frase1.includes("mun"));
console.log("11 - indexof() con " + frase1 + " resultado: " + frase1.indexOf("l"));
console.log("12 - length con " + frase1 + " resultado: " + frase1.length);
console.log("13 - localeCompare() con " + frase1 + " resultado: " + frase1.localeCompare("Hola"));
console.log("14 - match() con " + frase1 + " resultado: " + frase1.match("mundo"));
console.log("15 - padEnd() con " + frase1 + " resultado: " + frase1.padEnd(15, "!"));
console.log("16 - padStart() con " + frase1 + " resultado: " + frase1.padStart(15, "¿"));
console.log("17 - prototype resultado: " + String.prototype);
console.log("18 - repeat() con " + frase1 + " resultado: " + frase1.repeat(2));
console.log("19 - replace() con " + frase1 + " resultado: " + frase1.replace("Hola", "Adios"));
console.log("20 - replaceAll() con " + frase1 + " resultado: " + frase1.replaceAll("o", "0"));
console.log("21 - search() con " + frase1 + " resultado: " + frase1.search("mun"));
console.log("22 - slice() con " + frase1 + " resultado: " + frase1.slice(0, 5));
console.log("23 - split() con " + frase1 + " resultado: " + frase1.split(" "));
console.log("24 - startsWith() con " + frase1 + " resultado: " + frase1.startsWith(" Hola"));
console.log("25 - substr() con " + frase1 + " resultado: " + frase1.substr(0, 5));
console.log("26 - substring() con " + frase1 + " resultado: " + frase1.substring(0, 5));
console.log("27 - toLocaleLowerCase() con " + frase1 + " resultado: " + frase1.toLocaleLowerCase());
console.log("28 - toLocaleUpperCase con " + frase1 + " resultado: " + frase1.toLocaleUpperCase());
console.log("29 - trim() con " + frase1 + " resultado: " + frase1.trim());
console.log("30 - trimEnd() con " + frase1 + " resultado: " + frase1.trimEnd());
console.log("31 - trimStart() con " + frase1 + " resultado: " + frase1.trimStart());
console.log("32 - toLowerCase() con " + frase1 + " resultado: " + frase1.toLowerCase());
console.log("33 - toUpperCase() con " + frase1 + " resultado: " + frase1.toUpperCase());
console.log("34 - toString() con " + frase1 + " resultado: " + frase1.toString());
console.log("35 - valueOf() con " + frase1 + " resultado: " + frase1.valueOf());